<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Personnel;
use App\Models\Departement;

class PersonnelSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            'CHIMIE' => [
                'AL HOUARI GHALI',
                'ALAMI ANOUAR',
                'AZZAOUI KHALIL',
                'BENIKEN Mustapha',
                'BENJELLOUN MOHAMMED',
                'BENNANI MECHITA FARIDA',
                'BENZAKOUR MOHAMMED',
                'BOUAYAD ASMAE',
                'BOUDAD LAHCEN',
                'BOUKTAIB MOHAMED',
                'CHEMLAL SOUAD',
                'EL BAKALI IDRISS',
                'EL HAJJAJI FADOUA',
                'EL HALLAOUI MENANA',
                'EL YAZIDI MOHAMED',
                'FARAJ HASSANE',
                'HAMMOUDAN IMAD',
                'HERRADI SMAIEL',
                'IRAQI SALMA',
                'JANATI TAJDINE',
                'JILAL ISSAM',
                'KADDARI FATIHA',
                'KHALDI MOHAMMED',
                'LABRITI BRAHIM',
                'LACHKAR MOHAMMED',
                'LAHBABI NOURA',
                'LAHKIMI AMAL',
                'LAZRAQ MOHAMMED',
                'MCHARFI MOHAMMED',
                'MORADI KAMAL',
                'OUAMMOU ABDELKRIM',
                'OUARSAL RACHID',
                'OUDGHIRI HASSANI HICHAM',
                'RAIS ZAKIA',
                'RAKIB SOUAD',
                'SERRAR HOUDA',
                'SFAIRA MOUHCINE',
                'TACHIHANTE MOHAMED',
                'TALEB MUSTAPHA',
                'TITI ABDERRAHIM',
                'TOUIMI BENJELLOUN ADIL',
                'TOUNSADI HANANE',
            ],

            'MATHS' => [
                'AIT HAMMOU Mustapha',
                'AKDIM youssef',
                'AMRI Noura',
                'AZROUL ELHOUSSINE',
                'AZZOUZI ADNANE',
                'AZZOUZI IDRISSI MOSTAFA',
                'BADDI MOHAMED',
                'BARBARA Abdelkrim',
                'BENBOUZIANE HASSANE',
                'BENNOUNA JAOUAD',
                'CHEMS-EDDIN Mohamed Mahmoud',
                'CHOULLI HANAN',
                'ECH-CHERIF EL KETTANI MUSTAPHA',
                'EL AMRANI ABDELKHALEK',
                'EL BARRIMI OUSSAMA',
                'EL IDRISSI MOHAMMED',
                'EL KHALFAOUI RACHIDA',
                'EL KHALIFI MOHAMED',
                'EL MASSOUDI M\'HAMED',
                'ELFADIL Lhoussain',
                'EZ-ZOUAK Siham',
                'GADHI NAZIH ABDERRAZZAK',
                'HAMMOUTI OMAR',
                'HAMZAOUI Hassania',
                'KADAOUI ABBASSI MOHAMED TAHAR',
                'KIOUACH Driss',
                'KLILOU MOHAMMED',
                'LAFHIM LAHOUSSINE',
                'MEKKOUR Mounir',
                'MOUANIS HAKIMA',
                'MOUNIRH KARIM',
                'TOUAIL YOUSSEF',
                'ZAFRAR ABDERRAHIM',
                'ZAHOUAN YOUNESS',
                'ZAKI MONCEF',
                'ZGUITTI HASSANE',
            ],

            'INFORMATIQUE' => [
                'ABOUSSALEH ILYASSE',
                'AHERRAHROU NOURA',
                'ALAMI HAMZA',
                'ALAOUI ZIDANI KHALID',
                'BENLAHBIB ABDESSAMAD',
                'BENNANI Mohamed taj',
                'BOUAYAD ANAS',
                'Bouhoute Afaf',
                'BOUMHIDI JAOUAD',
                'CHENFOUR NOUREDDINE',
                'EL ABDERRAHMANI Abdellatif',
                'EL BEQQALI OMAR',
                'EL BOURAKADI DOUNIA',
                'EL FAHSSI KHALID',
                'EL FAZAZY KHALID',
                'EL GAROUANI SAID',
                'EL GHMARY MOHAMED',
                'EL-BATTEOUI Ismail',
                'ELFAR MOHAMED',
                'ELHAOUSSI FATIMA',
                'EN-NAHNAHI NOUREDDINE',
                'HJOUJI Amal',
                'LAMRINI MOHAMED',
                'LOQMAN Chakir',
                'MAHRAZ MOHAMED ADNANE',
                'NFAOUI EL HABIB',
                'OUFQIR ZAINAB',
                'RAMADAN HIBA',
                'RIFFI Jamal',
                'SABBANE FADOUA',
                'SABRI MY ABDELOUAHED',
                'SADQUI Azeddine',
                'SATORI KHALID',
                'SATORI Hassan',
                'TAIRI HAMID',
                'YAHYAOUY ALI',
                'ZINEDINE AHMED',
            ],

            // --- AJOUT DU DEPARTEMENT PHYSIQUE ---
            'Physique' => [
                'AARAB HASSANE',
                'ABABOU YAHYA',
                'ABOUNACHIT Omar',
                'AHFIR RACHID',
                'AMRI NABIL',
                'AZOUGARH ABDELHAFID',
                'AZOUAOUI ABDELOUAHID',
                'BENBRAHIM MOHAMMED',
                'BENCHEQROUNE ASMAE',
                'BENHALA BACHIR',
                'BENJELLOUN NADIA',
                'BENZAKOUR NAJIB',
                'BOSSOUFI Badre',
                'BOUKILI Bensalem',
                'BOUMHIDI ISMAIL',
                'BOUSLYKHANE KHALID',
                'CHAIBI NOREDDINE',
                'CHARQI MOHAMMED',
                'CHELLAKHI ABDELKHALEK',
                'CHERKANI HASSANI SALIMA',
                'CHERKANI HASSANI HIND',
                'CHIHAB YASSINE',
                'DERKAOUI ISSAM',
                'DIDISEDDIK ALI',
                'EL ALAMI RACHID',
                'EL BAKRI AYOUB',
                'EL BEKKALI CHAKIB',
                'EL GHZAOUI Mohammed',
                'EL OUGLI Abdelghani',
                'ELYAAKOUBI ALI',
                'ELBAHJAOUI Radouane',
                'FILALI MOHAMMED',
                'HALAQ HANAN',
                'HASSANI HAMID',
                'HATEL RHIZLANE',
                'KHARBACH JAOUAD',
                'LEMZIOUKA HAMANE',
                'MAGHNOUJ ABDELMAJID',
                'MASROUR Rachid',
                'MRHARRAB LAMIAE',
                'NAJI MOHAMED',
                'OUAZZANI CHAHIDI LAILA',
                'OUAZZANI TAYEBI HASSANI ABDALLAH',
                'RAHMOUNI ABDELAALI',
                'REZZOUK ABDELLAH',
                'RJEB ABDELILAH',
                'SALI AHMED',
                'SEFRITI SELMA',
                'SLAOUI KHADIJA',
                'TAHIRI ABDELLAH',
                'TALHA Lamiae',
                'TISSIR EL HOUSSAINE',
                'TOUTI RODOUAN',
                'ZOUHRI AMAL',
            ],
            // -------------------------------------

            'Géologie' => [
                'ADIL SAMIRA',
                'ATIF YOUSSEF',
                'AFENZAR Abdelkrim',
                'AHARMOUCH ABDELKRIM',
                'ASSAOUD SIHAM',
                'BAALI ABDENNASSER',
                'BELKASMI MOHAMED',
                'BEN ABBOU MOHAMED',
                'BENSLIMANE ANASSE',
                'CHAKIR SARA',
                'DRIOUCH YOUSSEF',
                'EL ARABI HASSAN',
                'EL ARBAOUI AMAL',
                'EL KHANCHOUFI ABDESSALAM',
                'EL QANDIL MOSTAFA',
                'Hminna Abdelkbir',
                'KARRAT LHOUCINE',
                'LOUAYA ABDELKARIM',
                'NTARMOUCHANT AHMED',
                'SABAOUI ABDELLAH',
                'SADIKI ABDELHAMID',
                'SMAILI Moulay HACHEM',
                'TEKIOUT BRAHIM',
            ],

            'Biologie' => [
                'ATIA FATIMA',
                'BAHHOU JAMILA',
                'BARI AMINA',
                'BEKKARI HICHAM',
                'BELGHALI Moulay Yassine',
                'BENDRISS AMRAOUI MOHAMMED',
                'BENJELLOUN AHMED SAMIR',
                'BENNIS NEZHA',
                'BENYAHYA MOHAMMED',
                'BENZIANE OUARITINI ZINEB',
                'BERRADA SANAE',
                'BOUIA ABDELHAK',
                'DAHCHOUR ABDELKADER',
                'DAMIRI LAILA',
                'DERWICH ELHOUSSAINE',
                'EL ALAMI RACHID',
                'EL ARABI ILHAM',
                'EL BALQUI ABDELKRIM',
                'EL HASSOUNI MOHAMMED',
                'EL-KARKOURI ABDENBI',
                'EL MESKAOUI Abdelmalek',
                'ERRCHIDI SOUMYA',
                'GUEMMOUH RAJA',
                'GUERNAOUI SOUAD',
                'HAMAMOUCH NOUREDDINE',
                'IRAQI HOUSSEINI ABDELILAH',
                'JAMAI LATIFA',
                'KHABBACH ABDELMAJID',
                'LAAROUSSI HASSAN',
                'LAAZIZ ADIL',
                'LAHMASS ILIASS',
                'LOUAHLIA SAID',
                'LOUASTE BOUCHRA',
                'Mabrouki Youness',
                'MAGOUL RABIA',
                'MERZOUKI MOHAMMED',
                'MEZIANE DRISS',
                'REMMAL ADNANE',
                'SEBAAI NAIMA',
                'SENHAJI RHAZI NAJIB',
                'TALBI FATIMA ZAHRA',
                'TILAOUI Mounir',
                'ZAABOUL FARAH',
            ],
        ];

        foreach ($data as $deptName => $enseignants) {
            // On cherche le département par nom (ex: "Physique", "Département de Physique", etc.)
            $departement = Departement::where('nom', 'LIKE', "%$deptName%")->first();

            if (!$departement) {
                // Si le département n'existe pas encore, on peut soit l'ignorer, soit le créer.
                // Ici on continue pour éviter les erreurs.
                continue;
            }

            foreach ($enseignants as $nom) {
                Personnel::updateOrCreate(
                    ['nom' => $nom],
                    ['departement_id' => $departement->id]
                );
            }
        }
    }
}
